default_environment: dev
project_id: 019ea29d-417d-7c17-83d1-9b5d6829e811
environments:
- name: dev
- name: staging
- name: prod
python: python3.11
plugins:
  extractors:
  - name: tap-postgres
    variant: meltanolabs
    pip_url: meltanolabs-tap-postgres
    config:
      database: $SUPABASE_DB
      filter_schemas:
      - public
      host: $SUPABASE_HOST
      port: $SUPABASE_PORT
      user: $SUPABASE_USER
      password: $SUPABASE_PASSWORD
  loaders:
  - name: target-bigquery
    variant: z3z1ma
    pip_url: git+https://github.com/z3z1ma/target-bigquery.git setuptools<80
    config:
      batch_size: 104857600
      credentials_json: $GCP_KEYFILE_PATH
      dataset: $BIGQUERY_DATASET
      denormalized: true
      flattening_enabled: true
      flattening_max_depth: 1
      method: batch_job
      project: $GCP_PROJECT_ID
